service: Portfolio
configValidationMode: error

provider:
  name: aws
  runtime: python3.8
  stackName: Portfolio-Python
  apiName: Portfolio-Python.2021 # API Gateway name
  lambdaHashingVersion: "20201221"

functions:
  portfolio_ping:
    handler: python/functions/ping.handle
    events:
      - http:
          method: GET
          path: ping
          cors: true

  asset_list: ${file(./serverless/currency.yml):list}

  test_cron:
    handler: python/functions/cron_test
    package:
      artifact: functions.zip
    events: 
     - schedule: cron(40 * * * * *)