service: PingService
configValidationMode: error
# lambdaHashingVersion: "20201221"

provider:
  name: aws
  runtime: python3.8

functions:
  #${file(./serverless/ping_copy.yml)}
  ping:
    handler: functions.ping.handle

    events:          
      - http:
          method: GET
          path: ping
          cors: true
      
