service: Portfolio
configValidationMode: error

provider:
  name: aws
  runtime: python3.8
  apiName: Portfolio # Use a custom name for the API Gateway API
  lambdaHashingVersion: "20201221"

functions:
  portfolio_ping:
    handler: ping.handle
    events:          
      - http:
          method: GET
          path: ping
          cors: true
      
