service: Portfolio
configValidationMode: error

provider:
  name: aws
  runtime: python3.8
  apiName: Portfolio # API Gateway name
  lambdaHashingVersion: "20201221"

functions:
  portfolio_ping:
    handler: ping.handle
    events:          
      - http:
          method: GET
          path: ping
          cors: true

  asset_list: ${file(./serverless/currency.yml):list}
      
