service: Portfolio
configValidationMode: error

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: "20201221"

functions:  
  #${file(./serverless/ping_copy.yml)}
  portfolio_ping:
    handler: ping.handle
    events:          
      - http:
          method: GET
          path: ping
          cors: true
      
