name: Deploy F# API

on:
  push:
    branches: 
    - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_STAGE: live
      AWS_REGION: eu-central-1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create datetime output
      id: datetime
      run: echo "::set-output name=datetime::$(date +'%Y-%m-%d_%H-%M-%S')"
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Buid VS solution
      run: dotnet build "FSharp project/Portfolio AWS API.sln" -c RELEASE