name: Deploy F# API
# Severless syntax: https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/

on:
  push:
    branches: 
    - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_STAGE: live
      AWS_REGION: eu-central-1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create datetime output
      id: datetime
      run: echo "::set-output name=datetime::$(date +'%Y-%m-%d_%H-%M-%S')"
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Buid VS solution
      run: dotnet build "FSharp project/Portfolio AWS API.sln" -c RELEASE
    #- name: Unit Tests
    #  run: dotnet test src/UnitTests/UnitTests.fsproj -c Release --no-build --filter "TestCategory!=SKIP_ON_DEPLOY"
    - name: Publish zip
      run: |
        dotnet publish "FSharp project/AwsLambda/AwsLambda.fsproj" -c RELEASE -o src/publish
        cd src/publish
        zip -r functions.zip ./*
    - name: Serverless
      uses: serverless/github-action@master
      with:
        # --deploy is deprecated but I don't know any other way to use multiple serverless.yml files
        args: deploy --config ./serverless/serverless.fsharp.yml --stage ${{env.AWS_STAGE}} --region ${{env.AWS_REGION}}