name: Deploy Python API

on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    env:
      AWS_STAGE: live
      AWS_REGION: eu-central-1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Zip python functions
        run: |
          cd python/functions
          zip -r functions.zip ./*.py
          cp functions.zip ../../functions.zip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Serverless Ping
        uses: serverless/github-action@master
        #serverless config credentials --provider aws --key AKIAIOSFODNN7EXAMPLE --secret wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
        # secrets:
        # - AWS_ACCESS_KEY_ID
        # - AWS_SECRET_ACCESS_KEY
        with:          
          # args: deploy --config ./serverless/ping.yml  --stage ${{env.AWS_STAGE}} --region ${{env.AWS_REGION}}
          args: deploy --config serverless/serverless.yml --stage ${{env.AWS_STAGE}} --region ${{env.AWS_REGION}}
        