name: Portfolio deploy master

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    env:
      AWS_STAGE: live
      AWS_REGION: eu-central-1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Zip python functions
        run: |
          cd functions
          zip -r functions.zip ./*.py
          cp functions.zip ../functions.zip

      - name: Serverless Ping
        uses: serverless/github-action@master
        # secrets:
        # - AWS_ACCESS_KEY_ID
        # - AWS_SECRET_ACCESS_KEY
        with:          
          # args: deploy --config ./serverless/ping.yml  --stage ${{env.AWS_STAGE}} --region ${{env.AWS_REGION}}
          args: deploy --stage ${{env.AWS_STAGE}} --region ${{env.AWS_REGION}}
