name: Deploy F# API
# Severless syntax: https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/

on:
  push:
    branches: 
    - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_STAGE: live
      AWS_REGION: eu-central-1
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create datetime output
      id: datetime
      run: echo "::set-output name=datetime::$(date +'%Y-%m-%d_%H-%M-%S')"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Substitute configuration variables
      uses: microsoft/variable-substitution@v1
      with:
        files: "FSharp project/AwsLambda/configuration.json"
      env:
        MongoDB_connection_string: ${{secrets.MONGODB_CONNECTION_STRING}}

    - name: Buid VS solution
      run: dotnet build "FSharp project/Portfolio AWS API.sln" -c RELEASE
    #- name: Unit Tests
    #  run: dotnet test src/UnitTests/UnitTests.fsproj -c Release --no-build --filter "TestCategory!=SKIP_ON_DEPLOY"
    - name: Publish zip
      run: |
        dotnet publish "FSharp project/AwsLambda/AWS Lambda.fsproj" -c RELEASE -o "FSharp project/publish"
        cd "FSharp project/publish"
        zip -r fsharp-functions.zip ./*

    - name: Serverless preparation
      run: | 
        echo move configuration file to the root folder, --config does not accept files in other positions
        mv ./serverless/serverless.fsharp.yml ./serverless.fsharp.yml

    - name: Serverless
      # bug: https://github.com/alex-piccione/portfolio-API-AWS/issues/51
      # Service Configuration is expected to be placed in a root of a service (working directory)
      #uses: serverless/github-action@master
      #with:
      #  args: deploy --config ./serverless/serverless.fsharp.yml --stage ${{env.AWS_STAGE}} --region ${{env.AWS_REGION}}

      uses: serverless/github-action@v1.53.0
      with:
        #--config is deprecated but I don't know any other way to use multiple serverless.yml files
        args: deploy --config serverless.fsharp.yml --stage ${{env.AWS_STAGE}} --region ${{env.AWS_REGION}}

