# This workflow is used to chech the code changes in pull requests

name: Pull Request Checks

on: 
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Buid VS solution
      id: build
      run: dotnet build "FSharp project/Portfolio AWS API.sln" -c RELEASE

  unit-tests:
    name: Unit Tests
    needs: [build]
    if: false == contains(github.event.pull_request.labels.*.name, 'pr:draft')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Unit Tests
      id: unit-tests
      run: dotnet test "FSharp project/UnitTests/UnitTests.fsproj" -c Release --no-build --filter "TestCategory!=SKIP_ON_DEPLOY"

  integration-tests:
    name: Integration Tests
    needs: [build]
    if: ${{ ! contains(github.event.pull_request.labels.*.name, 'pr:draft') }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Integration Tests
      id: integration-tests      
      run: dotnet test "FSharp project/IntegrationTests/IntegrationTests.fsproj" -c Release --no-build --filter "TestCategory!=SKIP_ON_DEPLOY"
